package cache

import (
	"os"

	"gitlab.com/mjwhitta/errors"
	"gitlab.com/mjwhitta/pathname"
)

// Cache related vars
var cacheDir string = pathname.ExpandPath("~/.cache/arTTY")
var cacheFile = "art.json"
var jsonDir = "arTTY_json"

// CustomJSONDir is the location where custom JSON files generated by
// the user are saved.
var CustomJSONDir string = pathname.ExpandPath(
	"~/.config/arTTY/" + jsonDir,
)

func init() {
	var e error
	var ok bool

	if ok, e = pathname.DoesExist(CustomJSONDir); e != nil {
		panic(errors.Newf("failed to access cache directory: %w", e))
	} else if !ok {
		if e = os.MkdirAll(CustomJSONDir, os.ModePerm); e != nil {
			e = errors.Newf("failed to create cache directory: %w", e)
			panic(e)
		}
	}
}
