package cache

import (
	"os"

	"gitlab.com/mjwhitta/pathname"
)

// Cache related vars
var cacheDir string = pathname.ExpandPath("~/.cache/arTTY")
var cacheFile = "art.json"
var imagesDir = "arTTY_images"

// CustomImagesDir is the location where custom JSON files generated by
// the user are saved.
var CustomImagesDir string = pathname.ExpandPath(
	"~/.config/arTTY/" + imagesDir,
)

func init() {
	var e error

	if !pathname.DoesExist(CustomImagesDir) {
		e = os.MkdirAll(CustomImagesDir, os.ModePerm)
		if e != nil {
			panic(e)
		}
	}
}
