#!/usr/bin/env bash

info() { echo -e "\e[32m[+] $@\e[0m"; }

usage() {
    echo "Usage: ${0/*\//} [OPTIONS]"
    echo
    echo "Parse arTTY_images repo and create ruby code for ArTTY"
    echo
    echo "Options:"
    echo "    -f, --force       Regenerate all images"
    echo "    -i, --imgs=DIR    Path to arTTY_images repo"
    echo
    exit $1
}

declare -a args
unset force imgs
output="../lib/arTTY/art/generated.rb"

while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-f"|"--force") force="-f" ;;
        "-h"|"--help") usage 0 ;;
        "-i"|"--imgs"*)
            case "$1" in
                "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
                *) shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
            esac
            imgs="$arg"
            ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ -z ${args[@]} ]] || set -- "${args[@]}"

[[ $# -eq 0 ]] || usage 2
[[ -n $imgs ]] || usage 3

for dir in \
    back_to_the_future \
    dc \
    evil_dead \
    kirby \
    legend_of_zelda \
    marvel \
    megaman \
    mighty_morphin_power_rangers \
    pokemon \
    pokemon/bulbapedia/I \
    pokemon/bulbapedia/II \
    pokemon/bulbapedia/III \
    sonic \
    street_fighter \
    teenage_mutant_ninja_turtles
do
    info "$dir"
    ./art_from_images $force -i $imgs/$dir -o cache -p
    [[ $? -eq 0 ]] || exit 1
done; unset dir

cat cache/*.rb >$output
