#!/usr/bin/env bash

### Helpers begin
set -o noglob
trap "clean 128" SIGINT # Ensure cleanup on ^C
check_deps() {
    for d in "${deps[@]}"; do
        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
    done; unset d
}
check_lock() {
    [[ -n $cache ]] || errx 126 "Cache is not defined"
    mkdir -p "$cache"
    if [[ -f "$cache.lock" ]]; then
        errx 125 "$cache.lock already exists"
    fi
    echo "$$" >"$cache.lock"
}
check_resume_file() {
    if [[ -f "$json" ]] && [[ -z $resume ]]; then
        warn "Resume file found" >&2
        while :; do
            # Prompt whether to overwrite or resume
            local a
            read -n 1 -p "Would you like to resume [y/n/q/c]: " -rs a
            echo

            case "$a" in
                "c") clean 0 ;;
                "n") write_resume_file; break ;;
                "q") exit 0 ;;
                "y") read_resume_file; resume="--resume"; break ;;
                *) echo "Invalid response, try again!" ;;
            esac
        done
    elif [[ -f "$json" ]]; then
        read_resume_file
    elif [[ -n $resume ]]; then
        errx 124 "No resume file found"
    else
        write_resume_file
    fi
}
clean() {
    if [[ ${1:-0} -eq 0 ]] || [[ ${1:-0} -eq 122 ]]; then
        [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
    fi
    [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
    [[ ${1:-0} -eq 125 ]] || [[ -z $cache ]] || rm -f "$cache.lock"
    show_cursor
    exit "${1:-0}"
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; clean "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
hide_cursor() { echo -en "\e[?25l"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
json_get() {
    if [[ -z $json ]] || [[ ! -f "$json" ]]; then
        return
    fi
    jq -cr ".$*" "$json" | sed -r "s/^null$//g"
}
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
show_cursor() { echo -en "\e[?25h"; }
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

read_resume_file() {
    pattern="$(json_get "pattern")"
}

usage() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS] [pattern]

Refresh art for ArTTY. Optionally provide a pattern to only refresh
selected categories.

Options:
    -f, --force          Generate images even if they already exist
    -h, --help           Display this help message
    --no color           Disable colorized output
    -r, --resume         Resume from a previous run
    -t, --threads=NUM    Use specified number of threads (default: 32)
    -v, --verbose        Do not hide parallel errors

EOF
    exit "$1"
}

write_resume_file() {
    [[ -n $cache ]] || return
    [[ -n $json ]] || return
    rm -rf "$cache"
    mkdir -p "$cache"

    cat >"$json" <<EOF
{
  "pattern": "$pattern"
}
EOF
}

declare -a args deps
unset force help pattern
color="true"
deps+=("git")
deps+=("jq")
parallel="true"
threads="32"

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-f"|"--force") force="true" ;;
        "-h"|"--help") help="true" ;;
        "--no-color") unset color ;;
        "-r"|"--resume") resume="--resume" ;;
        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
        "-v"|"--verbose") verbose="true" ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -le 1 ]] || usage 1

# Determine parallel situation
if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
    warn "Parallel is not installed, defaulting to single-threaded"
    unset parallel
fi

# Cite if needed
if [[ -n $parallel ]] && [[ ! -f "$HOME/.parallel/will-cite" ]]; then
    pvers="$(parallel --version | grep -ioPs "parallel \K\d+")"
    if [[ $pvers -lt 20181122 ]]; then
        mkdir -p "$HOME/.parallel"
        parallel --citation
    fi
    unset pvers
fi

# Save command line args
pattern="$1"

# Ensure script is called from the proper directory or with rake
[[ -f "./tools/${0##*/}" ]] || errx 2 "Use rake to call this script"

# Ensure directory exists and the submodule is updated
[[ -d "arTTY_images" ]] || mkdir -p arTTY_images
empty="$(find arTTY_images -maxdepth 1 -empty -print)"
[[ -z $empty ]] || git submodule update --init --recursive

# Throw error if submodule didn't get initialized/updated
empty="$(find arTTY_images -maxdepth 1 -empty -print)"
[[ -z $empty ]] || errx 3 "Submodule is missing"

# Move to submodule
cd ./arTTY_images

# Cache variables
hash="$(echo -n "$pattern" | sha256sum | awk '{print $1}')"
cache="$HOME/.cache/${0##*/}/$hash"
joblog="$cache/joblog.txt"
json="$cache/${0##*/}.json"

# Lock to prevent parallel issues
check_lock

# Check for resume file
[[ -z $parallel ]] || check_resume_file
hide_cursor

[[ -z $resume ]] || info "Resuming..."

info "Processing dataset for jobs"

dataset="$cache/${0##*/}.dataset"
if [[ ! -f "$dataset" ]]; then
    touch "$dataset"

    # Loop through specified categories
    while read -r dir; do
        category="${dir#./}"
        info "Processing ${category////-}"
        while read -r img; do
            echo "$dir|$img" >>"$dataset"
        done < <(find "$dir" -maxdepth 1 -name "*.png"); unset img
    done < <(
        find . -mindepth 1 -regextype posix-extended \
        -name "generated" -prune -o -name "todo" -prune -o \
        -name "tools" -prune -o -type d -iregex ".*$pattern.*" -print
    ); unset dir
fi
total="$(wc -l "$dataset" | awk '{print $1}')"
[[ $total -gt 0 ]] || errx 122 "No dataset provided"

subinfo "$total jobs to run"

# Create sub-script
script="/tmp/${0##*/}.parallel"
cat >"$script" <<EOF
#!/usr/bin/env bash

### Helpers begin
set -o noglob
err() { echo -e "\r${color:+\e[31m}[!] \$*\e[0m\e[K"; }
errx() { err "\${*:2}"; exit "\$1"; }
good() { echo -e "\r${color:+\e[32m}[+] \$*\e[0m\e[K"; }
info() { echo -e "\r${color:+\e[37m}[*] \$*\e[0m\e[K"; }
subinfo() { echo -e "\r${color:+\e[36m}[=] \$*\e[0m\e[K"; }
warn() { echo -e "\r${color:+\e[33m}[-] \$*\e[0m\e[K"; }
### Helpers end

# Constants
output="../arTTY_images/generated"

# Parse input
dir="\${1%%|*}"
dir="\${dir#./}"
dir="\${dir//_/-}"
img="\${1##*|}"

# Determine category
category="\${dir#./}"

# Determine art name
name="\${category////-}"
case "\$img" in
    *".jpg") name="\$name-\$(basename -s .jpg "\$img")" ;;
    *".png") name="\$name-\$(basename -s .png "\$img")" ;;
esac
name="\${name%_[0-9]*x[0-9]*}"
name="\${name//_/-}"

# Determine json filename
case "\$img" in
    *".jpg") filename="\$(basename -s .jpg "\$img")" ;;
    *".png") filename="\$(basename -s .png "\$img")" ;;
esac
filename="\${filename%_[0-9]*x[0-9]*}"
filename="\${filename//_/-}.json"

# Generate art
good "\$img => \$dir/\$filename"
if [[ ! -f "\$output/\$dir/\$filename" ]] || [[ "x$force" != "x" ]]
then
    mkdir -p "\$output/\$dir"
    arTTY -g "\$img" "\$name" >"\$output/\$dir/\$filename"
    failed="\$(find "\$output/\$dir/\$filename" -empty)"
    [[ -z \$failed ]] || err "Failed: \$dir/\$filename"
fi
EOF
chmod 700 "$script"

# Run sub-script
if [[ -n $parallel ]]; then
    parallel -a "$dataset" --bar --joblog ${resume:++}"$joblog" --lb \
        -P "$threads" -r $resume "$script" {}
    [[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2
else
    count="1"
    while read -r data; do
        echo -e "\r\e[K" >&2
        echo -en "${color:+\e[37m}[$count/$total]\e[0m\e[K\e[1A" >&2
        $script "$data"
        ((count += 1))
    done <"$dataset"; unset data
fi

clean
