name: GitHub Go CI
on:
  pull_request:
    branches: ["main"]
    paths: ["**.go"]
    types: ["edited", "opened"]
  push:
    branches: ["main"]
    paths: ["**.go"]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: actions/setup-go@v6
      with:
        go-version: "stable"
    - env:
        GOOS: "darwin"
      name: Lint (darwin)
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
    - env:
        GOOS: "linux"
      name: Lint (linux)
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
    - env:
        GOOS: "windows"
      name: Lint (windows)
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
    - name: Test coverage
      run: make cover
